# Generated by Django 4.1.1 on 2022-09-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Entry Type',
                'verbose_name_plural': 'Entry Types',
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('tipo_pagamento', models.CharField(max_length=100, verbose_name='Tipo Pagamento')),
                ('descrição', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.FloatField(default=0, max_length=10, verbose_name='Valor')),
                ('paid_at', models.DateTimeField(verbose_name='Pago em')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_account.bankaccount', verbose_name='Banco')),
                ('entry_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entries.entrytype', verbose_name='Entry Type')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
            bases=('core.basemodel',),
        ),
    ]
